In [2]:
import numpy as np 
import pandas as pd

In [3]:
df = pd.read_csv('filtered_dataAll.csv', sep=';', encoding='utf-8-sig') 
df

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (19,39) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Дата,ДатаДоставки,НомерЗаказаНаСайте,НовыйСтатус,СуммаЗаказаНаСайте,СуммаДокумента,МетодДоставки,ФормаОплаты,Регион,Группа2,...,Телефон_new,ЭлектроннаяПочта_new,Клиент,ID_SKU,ГородМагазина,МагазинЗаказа,НоваяМаржа,НоваяСуммаСтроки,ИспМаржа,НовСуммаЗаказаНаСайте
0,01.07.2017 00:00,06.07.2017 00:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00051334048,ИнтернетДоставка,NaN,"26,9",50,26.90,1634
1,01.07.2017 00:00,06.07.2017 00:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00051367351,ИнтернетДоставка,NaN,"26,9",50,26.90,1634
2,01.07.2017 00:00,06.07.2017 00:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00007611755,ИнтернетДоставка,NaN,"8,04",49,8.04,1634
3,01.07.2017 00:00,06.07.2017 00:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00014478250,ИнтернетДоставка,NaN,"5,79",40,5.79,1634
4,01.07.2017 00:00,06.07.2017 00:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00001209351,ИнтернетДоставка,NaN,"63,79",169,63.79,1634
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
473499,31.08.2017 23:42,04.09.2017 00:00,5412856_TR,Доставлен,3 189,3 189,Магазины,Безналичная,Химки (Московская область район),"ТЕКСТИЛЬ, ТРИКОТАЖ",...,55575653-55545554554979,118117_vu22@kamelia-dress.ru,Александр,IDL00031153351,ИнтернетДоставка,NaN,39,239,39.00,3189
473500,31.08.2017 23:42,04.09.2017 00:00,5412856_TR,Доставлен,3 189,3 189,Магазины,Безналичная,Химки (Московская область район),"ТЕКСТИЛЬ, ТРИКОТАЖ",...,55575653-55545554554979,118117_vu22@kamelia-dress.ru,Александр,IDL00031222856,ИнтернетДоставка,NaN,39,259,39.00,3189
473501,31.08.2017 23:42,04.09.2017 00:00,5412856_TR,Доставлен,3 189,3 189,Магазины,Безналичная,Химки (Московская область район),"ТЕКСТИЛЬ, ТРИКОТАЖ",...,55575653-55545554554979,118117_vu22@kamelia-dress.ru,Александр,IDL00033741553,ИнтернетДоставка,NaN,"202,73",670,202.73,3189
473502,31.08.2017 23:42,04.09.2017 00:00,5412856_TR,Доставлен,3 189,3 189,Магазины,Безналичная,Химки (Московская область район),ПОДГУЗНИКИ,...,55575653-55545554554979,118117_vu22@kamelia-dress.ru,Александр,ID10005324250,ИнтернетДоставка,NaN,"-18,25",755,-18.25,3189
473503,31.08.2017 23:42,07.09.2017 00:00,5413024_TR,Доставлен,1 194,1 194,Магазины,Безналичная,Ярославль,ПОДГУЗНИКИ,...,55575048-54534949515576,98109_bm24@gmail.com,Константин,IDL00028471149,ИнтернетДоставка,NaN,179,1045,179.00,1194

In [23]:
def generate_table(df, column_name="МесяцДатыЗаказа"): 
    columns_list = [column_name, 'КоличествоЧеков', 'Средний чек', 'СреднееЧислоТоваровЧека', 'Выручка', 'КоличествоТоваров', 'СредняяМаржа', 'ПроцентОтмен', ] 
    unique_values = df[column_name].unique()
    total = pd.DataFrame(columns=columns_list)
    for val in unique_values: 
        list_of_values = [val] 
        filtered_df = df[df[column_name] == val] 
        # Подсчет значений
        
        df_numb_check = filtered_df['НомерЗаказаНаСайте'].unique()               #кол-во чеков 
        numb_check = df_numb_check.size
        list_of_values.append(numb_check)  
        
        avarage_bill = int(round(filtered_df.groupby(['НомерЗаказаНаСайте']).mean()['НовСуммаЗаказаНаСайте'].mean())) #средний чек 
        list_of_values.append(avarage_bill) 
        
        avarage_numb_good = int(round(filtered_df.groupby(['НомерЗаказаНаСайте']).count()['НовСуммаЗаказаНаСайте'].mean())) #среднее кол-во товаров в  чеке
        list_of_values.append(avarage_numb_good) 
        
        profit = int(round(filtered_df['НоваяСуммаСтроки'].sum()))               #выручка 
        list_of_values.append(profit) 
        
        numb_good = filtered_df['МесяцДатыЗаказа'].size                          #кол-во товаров 
        list_of_values.append(numb_good) 
        
        absmargin = int(round(filtered_df['ИспМаржа'].sum()))                    #средняя маржа 
        list_of_values.append(absmargin/numb_check) 
        
        df_canceled = filtered_df['НомерЗаказаНаСайте'].unique()                 #процент отмен 
        numb_check = df_numb_check.size
        list_of_values.append(numb_check) 

        
        tmp_df = pd.DataFrame([list_of_values], columns=columns_list) 
        total = total.append(tmp_df, ignore_index=True)
    return total

In [24]:
pivot_table = generate_table(df, column_name="Телефон_new") 
pivot_table

,Телефон_new,КоличествоЧеков,Средний чек,СреднееЧислоТоваровЧека,Выручка,КоличествоТоваров,СредняяМаржа,ПроцентОтмен
0,55574948-52495050484877,1,1634,13,1585,13,497.000000,1
1,55575155-54535648525672,2,26169,2,26118,3,3497.500000,2
2,55575656-49565651494970,1,1915,11,1816,11,-10.000000,1
3,55574954-50555651515572,2,1284,3,2469,6,127.500000,2
4,55575348-57505757565774,7,2612,6,14061,43,375.142857,7
...,...,...,...,...,...,...,...,...
94533,55574949-50525350495673,1,2189,2,2090,2,358.000000,1
94534,55575649-55555555515377,1,2600,5,2600,5,1277.000000,1
94535,55575655-51565156554978,1,1998,1,1899,1,267.000000,1
94536,55575449-49534848495470,1,1540,6,1140,6,166.000000,1
94537,55574955-54485656535172,1,1199,1,1199,1,482.000000,1

In [25]:
pivot_table.to_csv('ВитринаРазмещенные.csv', index=False, sep=';', encoding='utf-8-sig')